# Generated by Django 4.0.8 on 2022-11-12 02:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Schema')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_schemas', to='contenttypes.contenttype', verbose_name='Content Type Model')),
            ],
            options={
                'verbose_name': 'Field Schema',
                'verbose_name_plural': 'Field Schemas',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Field')),
                ('type', models.CharField(choices=[('BooleanField', 'Boolean Field'), ('CharField', 'Char Field'), ('DateField', 'Date Field'), ('DateTimeField', 'DateTime Field'), ('DecimalField', 'Decimal Field'), ('EmailField', 'Email Field'), ('FileField', 'File Field'), ('FloatField', 'Float Field'), ('ImageField', 'Image Field'), ('IntegerField', 'Integer Field'), ('SlugField', 'Slug Field'), ('TextField', 'Text Field'), ('TimeField', 'Time Field')], default='CharField', max_length=50, verbose_name='Type of Field')),
                ('attrs', models.JSONField(blank=True, default=dict, null=True, verbose_name='Attributes')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.fieldschema')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
    ]
