# Generated by Django 3.2.12 on 2022-02-15 05:27

from django.db import migrations, models
import one.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("list_user", "Can get list of user")]},
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=one.users.utils.user_avatar_directory_path,
                verbose_name="Avatar of User",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Day of birth"),
        ),
    ]
