# Generated by Django 3.2.12 on 2022-03-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220215_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.TextField(
                blank=True, null=True, verbose_name="Status of User"
            ),
        ),
    ]
