# Generated by Django 3.2.13 on 2022-05-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220420_0015"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("vi", "Vietnamese"), ("en", "English")],
                default="en",
                max_length=2,
                verbose_name="User default language",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                choices=[("dark", "Dark theme"), ("light", "Light theme")],
                default="light",
                max_length=5,
                verbose_name="User default theme",
            ),
        ),
    ]
