# Generated by Django 3.2.11 on 2022-01-25 05:59

from django.db import migrations, models
import one.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=one.users.utils.user_avatar_directory_path,
                verbose_name="Avatar of User",
            ),
        ),
    ]
