# Generated by Django 3.2.12 on 2022-03-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('list_user', 'Can list user')]},
        ),
    ]
