# Generated by Django 3.2.12 on 2022-03-07 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import one.settings.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created on"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Last modified on"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Name of setting",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is protected"),
                ),
                (
                    "main_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=one.settings.utils.logo_directory_path,
                        verbose_name="Dashboard main logo",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_setting_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings_setting_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
            ],
            options={
                "permissions": [("list_%(class)s", "Can get list of %(class)s")],
                "abstract": False,
            },
        ),
    ]
