# Generated by Django 3.2.12 on 2022-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_init_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="setting",
            options={},
        ),
        migrations.AlterField(
            model_name="setting",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active"),
        ),
    ]
