# Generated by Django 4.0.8 on 2022-11-24 14:53

from django.db import migrations, models
import django.db.models.deletion
import one.contrib.auth.contexts.utils


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="context",
                        serialize=False,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=one.contrib.auth.contexts.utils.group_context_images_directory_path,
                        verbose_name="Avatar of group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Context",
                "verbose_name_plural": "Contexts",
                "db_table": "auth_group_context",
            },
        ),
    ]
