# Generated by Django 3.2.13 on 2022-05-02 16:40

import django.db.models.deletion
from django.db import migrations, models

import one.extend.riso_auth.contexts.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Context",
            fields=[
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="context",
                        serialize=False,
                        to="auth.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=one.extend.riso_auth.contexts.utils.group_context_images_directory_path,
                        verbose_name="Avatar of group",
                    ),
                ),
            ],
        ),
    ]
