# Generated by Django 3.2.15 on 2022-09-27 10:05

from django.db import migrations, models
import django.db.models.deletion
import one.contrib.sites.settings.utils


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_alter_options_ordering_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="setting",
                        serialize=False,
                        to="sites.site",
                        verbose_name="site",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=one.contrib.sites.settings.utils.setting_images_directory_path,
                        verbose_name="Favicon of site",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=one.contrib.sites.settings.utils.setting_images_directory_path,
                        verbose_name="Logo of site",
                    ),
                ),
                (
                    "mobile_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=one.contrib.sites.settings.utils.setting_images_directory_path,
                        verbose_name="Mobile logo of site",
                    ),
                ),
            ],
        ),
    ]
