# Generated by Django 4.0.8 on 2022-11-25 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0003_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='contenttype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='config', serialize=False, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
    ]
