# Generated by Django 3.2.13 on 2022-05-14 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllauthTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created on"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Last modified on"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("vi", "Vietnamese"), ("en", "English")],
                        default="vi",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        null=True,
                        verbose_name="Specific code for core app",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Subject of email",
                    ),
                ),
                (
                    "is_protected",
                    models.BooleanField(default=False, verbose_name="Is protected"),
                ),
                ("content", models.TextField(verbose_name="Html content")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails_allauthtemplate_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails_allauthtemplate_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("list_allauthtemplate", "Can list allauth email template")
                ],
                "unique_together": {("code", "language")},
            },
        ),
    ]
