# Generated by Django 4.0.8 on 2022-11-07 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "language",
                    models.CharField(
                        choices=[("vi", "Vietnamese"), ("en", "English")],
                        default="vi",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Menu ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name of Menu")),
                (
                    "render",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Render Json"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("lingual_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Item ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("link", "Link"),
                            ("accordion", "Accordion"),
                            ("section", "Section"),
                        ],
                        max_length=10,
                        verbose_name="Type of Item",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=255, verbose_name="Label of Item"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Link of Item",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Icon of Item",
                    ),
                ),
                (
                    "unique_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Unique Code of Item",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menu",
                    ),
                ),
            ],
        ),
    ]
