# Generated by Django 4.0.8 on 2022-11-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"verbose_name": "Menu", "verbose_name_plural": "Menus"},
        ),
        migrations.AlterModelOptions(
            name="menuitem",
            options={"verbose_name": "Menu Item", "verbose_name_plural": "Menu Items"},
        ),
    ]
