# Generated by Django 4.0.8 on 2022-11-09 13:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_menu_options_alter_menuitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
