# Generated by Django 4.0.8 on 2022-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('sidebar', 'Sidebar')], default='sidebar', max_length=255, verbose_name='Position'),
        ),
    ]
