# Generated by Django 3.2.12 on 2022-03-09 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "time_created",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created on"
                    ),
                ),
                (
                    "time_modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Last modified on"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("vi", "Vietnamese"), ("en", "English")],
                        default="vi",
                        max_length=2,
                        verbose_name="Language of %(class)s",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Name of page",
                    ),
                ),
                (
                    "url",
                    models.SlugField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL of page",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is active"),
                ),
                ("content", models.TextField(verbose_name="Page html context")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages_page_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages_page_last_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last modified by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
