# Generated by Django 3.2.12 on 2022-03-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_init_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('vi', 'Vietnamese'), ('en', 'English')], default='vi', max_length=2, verbose_name='Language'),
        ),
    ]
